[package]
name = "ipgen"
description = "A library for generating unique and reproducible IP addresses"
version = "0.0.1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rushmorem/ipgen"
documentation = "https://docs.rs/ipgen/0.0.1"
readme = "README.md"
keywords = ["IP", "IPv6"]
authors = ["Rushmore <rushmore@webenchanter.com>"]

[dependencies]
rust-crypto = "0.2.36"
ipnetwork = "0.10.0"
